{% set name = "stackstac" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stackstac-{{ version }}.tar.gz
  sha256: c8e9f65a9c6760f2d4bd345e0160c5bbe3ff4ce9787e106d1b21cd4c65fa3676

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.6,<4.0
    - dask >=2021.4.1,<2022.0.0
    - ipywidgets >=7.6.3,<8.0.0
    - numpy >=1.20.0,<2.0.0
    - pyproj >=3.0.0,<4.0.0
    - rasterio >=1.2.3,<2.0.0
    - scipy >=1.6.1,<2.0.0
    - xarray >=0.18,<1

test:
  imports:
    - stackstac
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://stackstac.readthedocs.io/en/latest/index.html
  summary: Load a STAC collection into xarray with dask
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
